### ISSUE TITLE
fundation目录下一个文件initializer_list.h缺失

### ISSUE THREAD

**Issue by czHappy** [HLhuanglang/TinySTL#1]
- initializer_list.h缺失，编译运行时1>E:\desk\c++\stl\TinySTL+-master\TinySTL-master\include\container\string.h(8,10): fatal error C1083: 无法打开包括文件: “fundation/initializer_list.h”: No such file or directory

```#ifndef STRING_H_
#define STRING_H_
#include <string.h>

#include <initializer_list>

#include "fundation/allocator.h"
#include "fundation/initializer_list.h"//这里
#include "fundation/iterator.h"

```

**Comment by HLhuanglang** [comment]
已修改，initializer_list.h头文件的实现依赖了编译器，无法通过自己编码实现，已经删除了这个头文件引用。
